---
title: "Simulation Results"
author: "Weijia Qian"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, repr.plot.width = 12, repr.plot.height = 8)
library(CCMHr)
library(gt)
library(kableExtra)
library(MASS)
library(patchwork)
library(refund)
library(scam)
library(splines)
library(tidyverse)

theme_set(theme_bw() + 
            theme(legend.position = "bottom",
                  ))
# theme(axis.text = element_text(size = 15),
#         axis.title = element_text(size = 15),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank(),
#         legend.position = "bottom",
#         legend.box.margin = margin(t = -20, b = 0),
#         legend.title = element_text(size = 15),
#         legend.text = element_text(size = 15))

# Define a custom color palette for the methods
my_colors <- c(
  "FTTM" = "#440154",
  # "mgcv LFCM" = "#414487",
  "LFCM" = "#2A788E",
  "loglogistic lfAFT" = "#7AD151",
  "lognormal lfAFT" = "#FDE725"
)
fig_dir <- "/Users/weijia/Research/Frailty/analysis/figures"

folder_path <- "/Users/weijia/Research/Frailty/outputs/20260210"
# folder_path <- "/Users/weijia/Research/Frailty/outputs/20260117"
rda_files <- list.files(path = folder_path, pattern = "\\.RDA$", full.names = TRUE)
all_results <- list()
for (i in 1:length(rda_files)) {
  all_results[[i]] <- loadRDa(rda_files[[i]])
}
```

### Computation Time
```{r}
all_info <- data.frame()
# Loop through all scenarios and iterations to extract 'info'
for (scenario in all_results) {
    all_info <- rbind(all_info, scenario $info)
}


# plot_time <- all_info %>%
#   ggplot(aes(factor(tau), time)) + 
#   geom_boxplot(fatten = 1.3) +
#   facet_grid(family~n_cluster, labeller = labeller(n_cluster = label_both, family = label_value), scales = "free") +
#   labs(x = expression(tau), y = "Computation Time")
# plot_time
# ggsave(file.path(fig_dir, "fig_sim_brier.jpeg"), plot_linear_Brier, width = 6, height = 4, dpi = 500)

```

### MISE for Estimated Coefficient Functions Across Iterations
```{r}
all_coef <- data.frame() 

# Loop through all scenarios and iterations to extract 'coef'
for (scenario in all_results) {
  tmp_data <- cbind(scenario$info, scenario$coef)
  all_coef <- rbind(all_coef, tmp_data)
}

table_coef <- all_coef %>%
  group_by(family, n_cluster, tau, sigma, censor_rate) %>%
  summarise(beta_mise = mean(beta_ise),
            beta_mean_cover = mean(beta_cover),
            tau2_mean_bias = mean(tau2_bias),
            tau2_mse = mean(tau2_se),
            tau2_mean_cover = mean(tau2_cover),
            sigma2_mean_bias = mean(sigma2_bias),
            sigma2_mse = mean(sigma2_se),
            sigma2_mean_cover = mean(sigma2_cover)
            )

table_beta_bias <- all_coef %>%
  group_by(beta_type, family, n_cluster, tau, sigma, censor_rate) %>%
  summarise(
    across(
      starts_with("beta_bias_"),
      ~ mean(.x, na.rm = TRUE)
    ),
    .groups = "drop"
  )  %>%
  pivot_longer(
    cols = starts_with("beta_bias_"),
    names_to = "beta_index",
    values_to = "bias"
  ) %>%
  mutate(
    beta_index = as.integer(gsub("beta_bias_", "", beta_index))
  )

plot_beta_bias <- ggplot(
  table_beta_bias,
  aes(x = beta_index, y = bias, color = factor(sigma), group = sigma)
) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.4) +
  geom_line(linewidth = 1) +
  # geom_point(size = 2) +
  facet_wrap(~ beta_type, scales = "free_y") +
  labs(
    x = "Function index",
    y = "Bias",
    color = expression(sigma),
    title = expression("Bias of"~beta(s))
  )
plot_beta_bias

# Box plot: MISE of beta(s)
plot_beta_mise <- all_coef %>%
  # filter(censor_rate == 0.1) %>%
  ggplot(aes(factor(sigma), beta_ise)) +
  geom_boxplot(fatten = 1.3) +
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("MISE of"~beta(s)))
plot_beta_mise

# Bar plot: coverage of beta(s)
plot_beta_cover <- all_coef %>%
  ggplot(aes(factor(sigma), beta_cover)) + 
  geom_bar(stat = "summary", fun = "mean", position = position_dodge()) +
  geom_hline(yintercept = 0.95, color = "red", lty = "dashed") +
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("Coverage of 95% CI for"~beta(s)))
plot_beta_cover
```


```{r tau2}
# Box plot: bias of tau2
plot_tau2_bias <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), tau2_bias)) + 
  geom_boxplot(fatten = 1.3) +
  geom_hline(yintercept = 0, color = "red", lty = "dashed")+
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("Bias of"~tau^2))
plot_tau2_bias

# Box plot: MSE of tau2
plot_tau2_mse <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), tau2_se)) + 
  geom_boxplot(fatten = 1.3) +
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("MSE of"~tau^2))
plot_tau2_mse

# Bar plot: coverage of tau2
plot_tau2_cover <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), as.numeric(tau2_cover))) + 
  geom_bar(stat = "summary", fun = "mean", position = position_dodge()) +
  geom_hline(yintercept = 0.95, color = "red", lty = "dashed")+
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("Coverage of 95% CI for"~tau^2))
plot_tau2_cover
```


```{r sigma2}
# Box plot: bias of sigma2
plot_sigma2_bias <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), sigma2_bias)) + 
  geom_boxplot(fatten = 1.3) +
  geom_hline(yintercept = 0, color = "red", lty = "dashed")+
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("Bias of"~sigma^2))
plot_sigma2_bias

# Box plot: MSE of sigma2
plot_sigma2_mse <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), sigma2_se)) + 
  geom_boxplot(fatten = 1.3) +
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("MSE of"~sigma^2))
plot_sigma2_mse

# Bar plot: coverage of sigma2
plot_sigma2_cover <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), as.numeric(sigma2_cover))) + 
  geom_bar(stat = "summary", fun = "mean", position = position_dodge()) +
  geom_hline(yintercept = 0.95, color = "red", lty = "dashed")+
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = expression("Coverage of 95% CI for"~sigma^2))
plot_sigma2_cover
```

```{r gamma0}
# Box plot: bias of intercept
plot_gamma0_bias <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), gamma_bias_1)) + 
  geom_boxplot(fatten = 1.3) +
  geom_hline(yintercept = 0, color = "red", lty = "dashed")+
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(sigma), y = "Bias of intercept")
plot_gamma0_bias

# Box plot: MSE of intercept
plot_gamma0_mse <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), gamma_se_1)) + 
  geom_boxplot(fatten = 1.3) +
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(tau), y = "MSE of intercept")
plot_gamma0_mse

# Bar plot: coverage of intercept
plot_gamma0_cover <- all_coef %>%
  filter(censor_rate == 0.25) %>%
  ggplot(aes(factor(sigma), as.numeric(gamma_cover_1))) + 
  geom_bar(stat = "summary", fun = "mean", position = position_dodge()) +
  geom_hline(yintercept = 0.95, color = "red", lty = "dashed")+
  facet_grid(~beta_type, labeller = label_value, scales = "free") +
  # facet_grid(sigma~n_cluster, labeller = labeller(n_cluster = label_both, sigma = label_both), scales = "free") +
  labs(x = expression(tau), y = "Coverage of 95% CI for intercept")
plot_gamma0_cover
```
